# Generated by Django 5.2.6 on 2025-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_face_encoding_profile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
